"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _home_page from './home-page.bones.json'

registerBones({
  "home-page": _home_page,
})
